export const courses = [
  {
    id: "1",
    title: "ASP.NET Core Masterclass",
    description: "تعلم بناء APIs احترافية وتطبيقات ويب متكاملة باستخدام ASP.NET Core من الصفر حتى الاحتراف.",
    longDescription: "كورس شامل بيغطي كل حاجة محتاجها عشان تبقى مطور Backend محترف. هتتعلم بناء RESTful APIs، التعامل مع قواعد البيانات، Authentication والـ Authorization، وDeployment على السيرفرات.",
    price: 99,
    category: "Backend Development",
    thumbnail: "https://picsum.photos/seed/course1/800/450",
    hours: 42,
    lessons: 87,
    level: "مبتدئ → محترف",
    language: "عربي",
    lastUpdate: "مايو 2026",
    rating: 4.9,
    students: 12400,
    includes: ["87 درس فيديو", "مشاريع عملية كاملة", "شهادة إتمام معتمدة", "وصول مدى الحياة", "دعم مباشر من المدرب", "كود المشاريع كامل"],
    curriculum: [
      { title: "مقدمة وإعداد البيئة", lessons: 8 },
      { title: "أساسيات ASP.NET Core", lessons: 14 },
      { title: "بناء RESTful APIs", lessons: 18 },
      { title: "قواعد البيانات مع Entity Framework", lessons: 16 },
      { title: "Authentication & Authorization", lessons: 12 },
      { title: "Deployment والـ Production", lessons: 10 },
      { title: "مشروع نهائي كامل", lessons: 9 },
    ],
    instructor: { name: "علي شاهين", title: "Senior .NET Developer", experience: "10+ سنوات خبرة" },
    content: "محتوى كورس ASP.NET Core Masterclass — فيديوهات + مشاريع عملية + كود source كامل.",
  },
  {
    id: "2",
    title: "React & Next.js Bootcamp",
    description: "من أساسيات React لبناء تطبيقات Next.js كاملة مع Server Side Rendering وAPI Routes.",
    longDescription: "الكورس الأشمل للـ Frontend Development بالعربي. هتتعلم React من الصفر، بعدين Next.js، وتبني تطبيقات حقيقية تنفع في سوق العمل.",
    price: 79,
    category: "Frontend Development",
    thumbnail: "https://picsum.photos/seed/course2/800/450",
    hours: 36,
    lessons: 72,
    level: "مبتدئ → متقدم",
    language: "عربي",
    lastUpdate: "أبريل 2026",
    rating: 4.8,
    students: 9800,
    includes: ["72 درس فيديو", "3 مشاريع حقيقية", "شهادة إتمام معتمدة", "وصول مدى الحياة", "مجموعة دعم خاصة", "ملفات المشاريع كاملة"],
    curriculum: [
      { title: "أساسيات JavaScript الحديث", lessons: 10 },
      { title: "React من الصفر", lessons: 16 },
      { title: "State Management", lessons: 12 },
      { title: "Next.js App Router", lessons: 14 },
      { title: "API Routes والـ Backend", lessons: 10 },
      { title: "Deployment على Vercel", lessons: 6 },
      { title: "مشروع نهائي", lessons: 4 },
    ],
    instructor: { name: "علي شاهين", title: "Full Stack Developer", experience: "8+ سنوات خبرة" },
    content: "محتوى كورس React & Next.js — مشاريع حقيقية وتطبيقات من الصفر.",
  },
  {
    id: "3",
    title: "Flutter Mobile Development",
    description: "ابني تطبيقات موبايل احترافية لـ iOS وAndroid بلغة Dart وFramework Flutter.",
    longDescription: "تعلم Flutter من الصفر وابني تطبيقات موبايل احترافية تشتغل على iOS وAndroid من كود واحد. الكورس بيركز على المشاريع العملية الحقيقية.",
    price: 69,
    category: "Mobile Development",
    thumbnail: "https://picsum.photos/seed/course3/800/450",
    hours: 38,
    lessons: 76,
    level: "مبتدئ → متقدم",
    language: "عربي",
    lastUpdate: "مارس 2026",
    rating: 4.7,
    students: 7200,
    includes: ["76 درس فيديو", "تطبيقين كاملين", "شهادة إتمام معتمدة", "وصول مدى الحياة", "دعم مباشر", "نشر على Store"],
    curriculum: [
      { title: "Dart Language Basics", lessons: 12 },
      { title: "Flutter Widgets الأساسية", lessons: 14 },
      { title: "State Management", lessons: 12 },
      { title: "Navigation والـ Routing", lessons: 8 },
      { title: "APIs والـ Backend Integration", lessons: 14 },
      { title: "نشر التطبيق على Store", lessons: 8 },
      { title: "مشروع نهائي", lessons: 8 },
    ],
    instructor: { name: "علي شاهين", title: "Mobile Developer", experience: "7+ سنوات خبرة" },
    content: "محتوى كورس Flutter — تطبيقات موبايل حقيقية من الفكرة للنشر على Store.",
  },
  {
    id: "4",
    title: "AI Tools for Developers",
    description: "استخدم أدوات الذكاء الاصطناعي في workflow البرمجة اليومي وضاعف إنتاجيتك 10 مرات.",
    longDescription: "الكورس الأول بالعربي اللي بيعلمك إزاي تستخدم الـ AI في شغلك كمطور بشكل احترافي. من Cursor وClaude Code لـ TestSprite وكل أدوات الـ workflow الحديثة.",
    price: 49,
    category: "Artificial Intelligence",
    thumbnail: "https://picsum.photos/seed/course4/800/450",
    hours: 22,
    lessons: 44,
    level: "متوسط",
    language: "عربي",
    lastUpdate: "مايو 2026",
    rating: 4.9,
    students: 15600,
    includes: ["44 درس فيديو", "workflow كامل جاهز", "شهادة إتمام معتمدة", "وصول مدى الحياة", "تحديثات مستمرة", "قائمة الأدوات المجانية"],
    curriculum: [
      { title: "مقدمة لـ AI في البرمجة", lessons: 6 },
      { title: "Cursor وClaude Code", lessons: 10 },
      { title: "AI Testing مع TestSprite", lessons: 8 },
      { title: "Workflow كامل من الفكرة للـ Deploy", lessons: 10 },
      { title: "أدوات التصميم بالـ AI", lessons: 6 },
      { title: "مشروع كامل بالـ AI", lessons: 4 },
    ],
    instructor: { name: "علي شاهين", title: "AI Tools Expert", experience: "6+ سنوات خبرة" },
    content: "محتوى كورس AI Tools — Cursor, Claude Code, TestSprite وأكتر.",
  },
  {
    id: "5",
    title: "Clean Code & Software Architecture",
    description: "تعلم كيف تكتب كود نظيف قابل للصيانة وتطبق مبادئ SOLID وأفضل معمارية للمشاريع.",
    longDescription: "الفرق بين المطور العادي والمطور المحترف هو جودة الكود. تعلم SOLID Principles، Design Patterns، Clean Architecture، وكيف تكتب كود يفتخر بيه أي فريق.",
    price: 39,
    category: "Software Engineering",
    thumbnail: "https://picsum.photos/seed/course5/800/450",
    hours: 28,
    lessons: 56,
    level: "متوسط → متقدم",
    language: "عربي",
    lastUpdate: "فبراير 2026",
    rating: 4.8,
    students: 6400,
    includes: ["56 درس فيديو", "Code Reviews حقيقية", "شهادة إتمام معتمدة", "وصول مدى الحياة", "أمثلة قبل وبعد", "مرجع SOLID كامل"],
    curriculum: [
      { title: "Clean Code Principles", lessons: 10 },
      { title: "SOLID Principles", lessons: 12 },
      { title: "Design Patterns", lessons: 14 },
      { title: "Clean Architecture", lessons: 10 },
      { title: "Code Review وRefactoring", lessons: 6 },
      { title: "تطبيق على مشروع حقيقي", lessons: 4 },
    ],
    instructor: { name: "علي شاهين", title: "Software Architect", experience: "12+ سنوات خبرة" },
    content: "محتوى كورس Clean Code — SOLID Principles, Design Patterns, وأكتر.",
  },
];

export function getCourseById(id) {
  return courses.find(c => c.id === id) || null;
}
